apiVersion: apps/v1 #  
kind: Deployment
metadata:
  name: onec
  namespace: onec
  labels:
    version: 8-3-14-2095
    app: onec
spec:
  selector:
    matchLabels:
      app: onec
  replicas: 1
  template:
    metadata:
      labels:
        app: onec
      namespace: onec
    spec:
      # serviceAccountName: onec-kubeonec-sa
      containers:
      - name: oscript-rac
        image: demoncat/onec:oscript-8.3.16.1659
        command: ['sh', '-c', 'echo The app is running! && sleep 3600']
      # volumes:
      #   - name: nethasp
      #     configMap:
      #       name: nethasp
      #       items:
      #       - key: nethasp.conf
      #         path: /opt/1C/v8.3/x86_64/conf



